mercadolibre/fury_andesui-android

PULL_REQUEST_TEMPLATE.md

The Pull Request Template had an issue with checkboxes.
Removed unnecessary spaces for the checkboxes that made those checkboxes to not be shown properly once completed.
GitHub experience.
N/A
N/A

Updated Pull Request Template

---

README.md

Circle CI badge was not shown properly.
Added develop branch reference to the Circle CI badge link.
Repo
N/A
N/A

Updated Circle CI badge on README.md

---

CHANGELOG.md
components/src/main/java/com/mercadolibre/android/andesui/button/AndesButton.kt
components/src/main/java/com/mercadolibre/android/andesui/button/factory/AndesButtonAttrsParser.kt
components/src/main/java/com/mercadolibre/android/andesui/button/factory/AndesButtonConfigurationFactory.kt
components/src/main/java/com/mercadolibre/android/andesui/button/factory/IconConfig.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/ButtonShowcaseActivity.kt
demoapp/src/main/res/values/strings.xml
gradle.properties

AndesButton hierarchy could not be updated after its creation. This PR includes changes to support dynamically change its configuration.
AndesButton configuration can be updated in runtime, consistently with AndesMessage
(see #7).
This PR adds the possibility to update the button hierarchy or text after its creation. See the following example for an XML button created :
```
<com.mercadolibre.android.andesui.button.AndesButton
android:id="@id/button_id"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
app:andesButtonSize="large"
app:andesButtonHierarchy="loud" />
```
Now, the button hierarchy can be updated on runtime by accessing its properties:
```
button_id.hierarchy = AndesButtonHierarchy.TRANSPARENT
```
`AndesButton` …

Dynamic changes for AndesButton properties

---

CHANGELOG.md
demoapp/README.md
demoapp/build.gradle
demoapp/src/main/AndroidManifest.xml
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/AndesSpecs.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/MainActivity.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ButtonShowcaseActivity.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/MessageShowcaseActivity.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/WhatsNewActivity.kt
demoapp/src/main/res/layout/andesui_demoapp_main.xml
demoapp/src/main/res/layout/andesui_demoapp_whatsnew.xml
demoapp/src/main/res/layout/andesui_loud_buttons_showcase.xml
demoapp/src/main/res/layout/andesui_message_showcase.xml
demoapp/src/main/res/layout/andesui_quiet_buttons_showcase.xml
demoapp/src/main/res/layout/andesui_transparent_buttons_showcase.xml
demoapp/src/main/res/raw/andesui_demoapp_changelog.md
demoapp/src/main/res/values/dimens.xml
demoapp/src/main/res/values/strings.xml
gradle.properties

I want to have the best UI lib app in the world
- Many minor fixes included such as:
- Spanish ==> English translations
- Android package fixes
- What's new section added automatically
- Home page redesign
- Added library version to the action bar
- Link to the Andes website at the home page as well as for each component showcase
None, only the Andes app.
None

Many app improvements and fixes

---

CHANGELOG.md
components/src/test/java/com/mercadolibre/android/andesui/button/AndesButtonTest.kt
components/src/test/java/com/mercadolibre/android/andesui/message/AndesMessageConfigurationLoudTest.kt
components/src/test/java/com/mercadolibre/android/andesui/message/AndesMessageConfigurationQuiet.kt
gradle.properties

Merge/release 2.0 develop

---

components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextarea.kt
components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt

Adding constructors to programmatic support on Textfield and Textarea
- [] I have coded an example inside the Demo App,
https://proandroiddev.com/how-to-maximize-androids-ui-reusabili …

programmatic support

---

components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTexfieldAttrsParser.kt
components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTextareaAttrsParser.kt
components/src/main/res/textfield/values/attrs.xml
demoapp/src/main/res/layout/andesui_textfield_showcase.xml

Change hint to placeholder.
Andes Textfield - Andes Textarea

fixing naming placeholder

---

components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt

Clear Icon only appears on text.
Textfield

clear on text

---

components/build.gradle
components/src/main/java/com/mercadolibre/android/andesui/badge/AndesBadge.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/border/AndesBadgeBorder.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/border/AndesBadgeBorderInterface.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/factory/AndesBadgeAttrsParser.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/factory/AndesBadgeConfigurationFactory.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/hierarchy/AndesBadgeHierarchy.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/hierarchy/AndesBadgeHierarchyInterface.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/modifier/AndesBadgeModifier.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/modifier/AndesBadgeModifierInterface.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/size/AndesBadgeSize.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/size/AndesBadgeSizeInterface.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/type/AndesBadgeType.kt
components/src/main/java/com/mercadolibre/android/andesui/badge/type/AndesBadgeTypeInterface.kt
components/src/main/res/badge/layout/andes_layout_badge.xml
components/src/main/res/badge/values/attrs.xml
components/src/main/res/badge/values/dimens_badge.xml
components/src/test/java/com/mercadolibre/android/andesui/badge/AndesBadgeConfigurationLoudTest.kt
components/src/test/java/com/mercadolibre/android/andesui/badge/AndesBadgeConfigurationQuietTest.kt
demoapp/src/main/AndroidManifest.xml
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/AndesSpecs.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/MainActivity.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/BadgeShowcaseActivity.kt
demoapp/src/main/res/layout/andesui_demoapp_main.xml
demoapp/src/main/res/layout/andesui_loud_badges_showcase.xml
demoapp/src/main/res/layout/andesui_quiet_badges_showcase.xml
demoapp/src/main/res/values/dimens.xml
demoapp/src/main/res/values/strings.xml

Implement the AndesBadge (Pill) component defined by the UX team
AndesBadge (Pill) is a component defined here.
AndesBadge
[AndesBadge Frontify](https://company-161429.frontify.com/d/kxHCRixezmfK/n-a#/componentes/badge)
Whether you are an …

Added Andes badge

---

CHANGELOG.md
components/src/main/res/button/values/attrs.xml
gradle.properties

In order to enable R8, AGP 3.6, Gradle 5.6.4, and AndroidX in Wallet, we need to get rid of this compiling problem.
The problem was that the format was not defined, we added it and made a local experimental lib and test it in the wallet =)
defines the type of the attr
N/A
Is highly probable that this new code directly affects one (or more?) components inside this lib. Tell …

Add format to public Attr

---

demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/TagShowcaseActivity.kt

Clear feedback to the Andes app users
I'm justo fixing a typo
Only the Andes app
N/A

TestApp: Fix typo in error message

---

components/src/main/java/com/mercadolibre/android/andesui/tag/AndesTagSimple.kt
components/src/main/java/com/mercadolibre/android/andesui/tag/factory/AndesTagSimpleAttrsParser.kt
components/src/main/java/com/mercadolibre/android/andesui/tag/factory/AndesTagSimpleConfigurationFactory.kt
components/src/main/java/com/mercadolibre/android/andesui/tag/leftcontent/AndesTagLeftContentInterface.kt
components/src/main/java/com/mercadolibre/android/andesui/tag/rightcontent/AndesTagRightContentInterface.kt
components/src/main/java/com/mercadolibre/android/andesui/tag/type/AndesTagType.kt
components/src/main/java/com/mercadolibre/android/andesui/tag/type/AndesTagTypeInterface.kt
components/src/main/res/textfield/layout/andes_layout_simple_tag.xml
components/src/main/res/values/attrs.xml
components/src/test/java/com/mercadolibre/android/andesui/tag/AndesTagSimpleTest.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/TagShowcaseActivity.kt
demoapp/src/main/res/values/strings.xml
gradle.properties

Se hicieron cambios menores reportado por UX
- Se cambió el color del texto default
- Se eliminó el type "Neutral"
- Se modifico el margen del icono dismiss
- Se agregó un stroke a la imagen (left content)

Minor tag changes

---

CHANGELOG.md
components/src/main/java/com/mercadolibre/android/andesui/message/AndesMessage.kt
components/src/main/java/com/mercadolibre/android/andesui/message/factory/AndesMessageConfigurationFactory.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/MessageShowcaseActivity.kt
demoapp/src/main/res/layout/andesui_demoapp_main.xml
demoapp/src/main/res/layout/andesui_message_showcase.xml
demoapp/src/main/res/layout/andesui_message_showcase_change.xml
demoapp/src/main/res/raw/andesui_demoapp_changelog.md
demoapp/src/main/res/values/dimens.xml
demoapp/src/main/res/values/strings.xml

Se actualiza la demoapp en la parte de AndesMessage para utilizar todos los componentes de Andes.
- AndesMessage

Minor changes demoapp

---

components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt

Permite hacer foco en textfield para levantar el teclado
AndesTextField
- [x ] This code includes improvements to an existent component

Text field focus

---

components/src/main/java/com/mercadolibre/android/andesui/thumbnail/AndesThumbnail.kt
demoapp/src/main/res/raw/andesui_demoapp_changelog.md

Add the getter and setter to the Andes Thumbnail image property.
Add the getter and setter to the Andes Thumbnail image property to allow change the image programmatically.
AndesThumbnail
[AndesThumbnail Frontify](https://company-161429.frontify.com/d/kxHCRixezmfK/n-a#/componentes/thumbnail-1589997379)
Are you sure you followed all those steps? In such …

Added getter and setter for AndesThumbnail's image

---

CHANGELOG.md
gradle.properties

AndesUI v2.9.0 -> Develop

---

CHANGELOG.md

I only make some improvements to the changelog

Better changelog format

---

CHANGELOG.md
demoapp/src/main/res/raw/andesui_demoapp_changelog.md
gradle.properties

v2.10.0 -> Develop

---

CHANGELOG.md
components/src/main/java/com/mercadolibre/android/andesui/progress/AndesProgressIndicatorIndeterminate.kt
gradle.properties

Fix Leak LoadingSpinner

---

.github/workflows/hello-to-news-contributions.yml

I want to build a world class project and I think this is a nice touch to help increase engagement with the Andes project
This PR just setup the GitHub Action [first-interaction](https://github.com/marketplace/actions/auto-message-for-pr-s-and-issues) to the repository
It will comment on every issue/pull request to greet new contributors
None, just the CI pipeline

Setup first-interaction GitHub Action

---

CHANGELOG.md
demoapp/src/main/res/raw/andesui_demoapp_changelog.md

v2.10.1 -> develop

---

.github/workflows/hello-to-news-contributions.yml

Fix look & feel for hello-to-news-contributions GitHub Action

---

.circleci/config.yml
CHANGELOG.md
components/src/main/java/com/mercadolibre/android/andesui/button/AndesButton.kt
components/src/main/java/com/mercadolibre/android/andesui/message/factory/AndesMessageConfigurationFactory.kt
components/src/main/java/com/mercadolibre/android/andesui/progress/AndesProgressIndicatorIndeterminate.kt
components/src/main/java/com/mercadolibre/android/andesui/progress/LoadingSpinner.kt
components/src/main/java/com/mercadolibre/android/andesui/progress/factory/AndesProgressAttrsParser.kt
components/src/main/java/com/mercadolibre/android/andesui/progress/factory/AndesProgressConfigurationFactory.kt
components/src/main/java/com/mercadolibre/android/andesui/progress/size/AndesProgressSize.kt
components/src/main/java/com/mercadolibre/android/andesui/tag/AndesTagSimple.kt
components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
components/src/main/java/com/mercadolibre/android/andesui/thumbnail/factory/AndesThumbnailAttrsParser.kt
demoapp/build.gradle
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ButtonShowcaseActivity.kt
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ProgressShowcaseActivity.kt
demoapp/src/main/res/raw/andesui_demoapp_changelog.md
gradle.properties

Este PR fue generado automaticamente para la migracion de API 29, donde se consideraron las variables _maxApiLevel_ y _androidBuildToolsVersion_ teniendo en cuenta como estan configurados la mayoria de los repos. Para mas detalles de la migracion, chequear la [Wiki](https://sites.google.com/mercadolibre.com/mobile/gu%C3%ADas-y-problemas/gu%C3%ADas-de-migraci%C3%B3n/migraci%C3%B3n-api-29-android) donde podes encontrar info actualizada sobre los deadlines, flujos, pruebas y cambios necesarios. Tambien podes mirar el [Workplace](https://meli.workplace.com/groups/607167069708629/permalink/967013757057290/). Para dudas generales, estamos en el channel [help-android-api29](https://meli.slack.com/archives/C016G4H866R) en Slack.

[Trivial] Migration API 29

---

CHANGELOG.md
components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
demoapp/src/main/res/raw/andesui_demoapp_changelog.md

Both fields are useful to customize input filter and allowed characters.
We need to customize filters and allowed digits. This solution is simple and flexible enough to apply it to any workaround.
The primary use on this is to allow us to filter and mas numbers with custom DecimalFormatSymbols and with fixed amount of decimals.
How this work:
Assign the property textDigits programatically and will impact as …

Expose textFilter and textDigits

---

config/android/android-lint-components.xml
demoapp/build.gradle
demoapp/src/main/res/raw/andesui_demoapp_changelog.md

Add proguard in buildTypes->release

---

CHANGELOG.md
demoapp/src/main/res/layout/andesui_demoapp_main.xml
demoapp/src/main/res/raw/andesui_demoapp_changelog.md
demoapp/src/main/res/values/strings.xml

This PR only modifies the Andes App by sorting home buttons alphabetically.

Sort buttons form the Andes App alphabetically

---

CHANGELOG.md
demoapp/src/main/res/raw/andesui_demoapp_changelog.md
gradle.properties

Bump version

---

coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/model/AndesWalkthroughCoachmark.kt
coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/presenter/CoachmarkPresenter.kt
coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/CoachmarkView.kt
coachmark/src/test/java/com/mercadolibre/android/andesui/coachmark/presenter/CoachmarkPresenterTest.kt
demoapp/src/main/res/raw/andesui_demoapp_changelog.md

- Andes Coachmark: force only portrait mode and fix scroll up
- Coachmark

Fix Coachmark Portrait and Scroll

---

CHANGELOG.md
demoapp/src/main/res/raw/andesui_demoapp_changelog.md

Fix changelog

---

CHANGELOG.md
components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfieldCode.kt
components/src/main/res/layout/andes_layout_list_item_chevron.xml
components/src/main/res/layout/andes_layout_list_item_simple.xml
demoapp/build.gradle
demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ListShowcaseActivity.kt
demoapp/src/main/res/raw/andesui_demoapp_changelog.md
dependencies.gradle
gradle.properties

Migramos a constraint layout v2 y probamos todos los componentes.

Migración Constraint Layout 2

---

demoapp/src/main/res/raw/andesui_demoapp_changelog.md
gradle.properties

Bump demoapp

---

CHANGELOG.md
components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt

se agregan estilos para la correcta visualización en api level < 21

api level < 21 fix

---

.github/stale.yml
CHANGELOG.md

Se cambia la configuración del bot en state.yml para que las reglas solo apliquen a los pulls
Evitar que los issues se cierren solos, solo deberían cerrarse los que ya se hayan finalizado.
N/A
This is a UI library, delight us with some …

Disable bot for issues

---

CHANGELOG.md
components/src/main/java/com/mercadolibre/android/andesui/message/AndesMessage.kt
demoapp/src/main/res/raw/andesui_demoapp_changelog.md
gradle.properties

We fix the constructor with thumbnail compatibility in java classes.
The annotation will create constructors in java to use optional parameters.
AndesMessage
This …

[Fix] Constructor overload java

---

CHANGELOG.md
demoapp/src/main/res/layout/andesui_dropdown_form_showcase.xml
demoapp/src/main/res/layout/andesui_dropdown_standalone_showcase.xml
demoapp/src/main/res/raw/andesui_demoapp_changelog.md

Added a ScrollView container to Dropdown Showcase ui in order to avoid cutting part of the ui in small devices.
Demoapp: Dropdown showcase …

[Fix] Demoapp Dropdown Showcase ui cut

---

coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/CoachmarkView.kt
coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/CoachmarkScrollessView.kt
components/src/main/res/values/color_palette.xml

- Aplicamos un 90% de opacidad al color de background del Walkthrough.
Is highly probable that this new code directly affects one (or more?) components inside …

Applying a darker color for the walkthrough background
