- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/message/AndesMessage.kt
- components/src/main/java/com/mercadolibre/android/andesui/message/factory/AndesMessageAttrsParser.kt
- components/src/main/java/com/mercadolibre/android/andesui/message/factory/AndesMessageConfigurationFactory.kt
- components/src/main/java/com/mercadolibre/android/andesui/message/state/AndesMessageState.kt
- components/src/main/java/com/mercadolibre/android/andesui/message/state/AndesMessageStateInterface.kt
- components/src/main/java/com/mercadolibre/android/andesui/message/state/AndesMessageType.kt
- components/src/main/res/message/layout/andesui_layout_message.xml
- components/src/main/res/message/values/attrs.xml
- components/src/main/res/message/values/dimens_message.xml
- demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/MessageShowcaseActivity.kt
- demoapp/src/main/res/layout/andesui_demoapp_main.xml
- demoapp/src/main/res/layout/andesui_message_showcase.xml
- demoapp/src/main/res/values/strings.xml
- gradle.properties
An AndesMessage couldn't be found by its id (even if you specify one id via XML code).
- We were calling super(context) instead of super(context, attrs), so ID was getting null and then a random ID was assigned to the AndesMessage: Impossible to found.
- UX team said that Highlight was not the right name for one of the states. It should be called Neutral. We had aligned this naming :)
- We had some free time to play with Android APIs so we decided to add `animateLayoutChanges` flag.
AndesMessage
https://company-161429.frontify.com/d/kxHCRixezmfK/n-a#/componentes/message
> Fixes: Type name update + findViewById not working

- components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/content/AndesTexfieldContent.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/content/AndesTextfieldContentInterface.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTexfieldAttrsParser.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTextfieldConfigurationFactory.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/state/AndesTextfieldState.kt
- components/src/main/res/textfield/layout/andes_layout_texfield.xml
- components/src/main/res/textfield/values/attrs.xml
- components/src/main/res/textfield/values/dimens.xml
- components/src/main/res/textfield/values/dimens_textfield.xml
- components/src/main/res/textfield/values/strings.xml
- demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/TextfieldShowcaseActivity.kt
- demoapp/src/main/res/layout/andesui_textfield_showcase.xml
Adding right and left texfield contents.
Textfield
> textfield right and left component

- demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/MessageShowcaseActivity.kt
- demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/TextfieldShowcaseActivity.kt
- demoapp/src/main/res/layout/andesui_textfield_showcase_change.xml
- demoapp/src/main/res/values/strings.xml
Have an example of how to use enums without mapping strings
All of them and the demoapp too
> Chage all when in demoapp to enum.valueOf(string)

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/content/AndesTextfieldContentInterface.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTextfieldConfigurationFactory.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/state/AndesTextfieldState.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/state/AndesTextfieldStateInterface.kt
- components/src/main/res/textfield/layout/andes_layout_textfield.xml
- components/src/main/res/textfield/values/dimens_textfield.xml
- components/src/main/res/textfield/values/strings.xml
- components/src/test/java/com/mercadolibre/android/andesui/textfield/AndesTexfieldContentInterfaceTest.kt
- demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/TextfieldShowcaseActivity.kt
- demoapp/src/main/res/layout/andesui_textfield_showcase_change.xml
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
- demoapp/src/main/res/values/dimens.xml
- demoapp/src/main/res/values/strings.xml
Fixes en textfield y cambios mínimos en la testapp.
**Fixes en textfield**
- El helper y el counter se veía con el state "read-only"
- El padding izquierdo del textfield está mal con el state "read-only" (desalineado al label)
- En "disabled" y "read-only" el action no se pone en disabled.
- Error con el helper.
**Se cambio**
- Se agregó toast con el callback de "action"
- Se agregó la opción "None" para el "Prefix" y "Sufix".
- Cambió el nombre de "Prefix" y "Sufix" a "Left content" y "Right content" respectivamente.
- En la testapp, el counter se puso por defecto en 50.
Whether you are an Android or iOS developer and if you're still …
> Minor errors in textfield

- components/src/main/java/com/mercadolibre/android/andesui/badge/AndesBadgePill.kt
La AndesBadgePill provocaba un crash de la App cuando se cambiaba programaticamente Type, Hierarchy o Size, porque la altura se cambiaba con un ViewGroup.LayoutParam mientras que se espera un LinearLayout.LayoutParam.
AndesBadgePill
[AndesBadge Frontify](https://company-161429.frontify.com/d/kxHCRixezmfK/n-a#/componentes/badge)
> Fix AndesBadgePill error

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/font/TextViewExtension.kt
- components/src/main/java/com/mercadolibre/android/andesui/font/TypefaceHelper.kt
- components/src/main/java/com/mercadolibre/android/andesui/font/TypefaceSpanCompat.kt
- components/src/main/java/com/mercadolibre/android/andesui/font/TypefaceSpanFactory.kt
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
- gradle.properties
Se elimina el soporte de las fuentes. 
Se va a empezar a impulsar a los equipos a usar Andes (cada componente ya te resuelve la font)
> Se depreca el soporte de las fuentes

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextarea.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTexfieldAttrsParser.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTextareaAttrsParser.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTextfieldConfigurationFactory.kt
- components/src/test/java/com/mercadolibre/android/andesui/textfield/AndesTextfieldTest.kt
- demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/TextfieldShowcaseActivity.kt
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
- gradle.properties
Se agregó TextWatcher en el TextField y TextArea. Era requerido por algunos equipos para poder tener un listener cuando el TextField cambiara.
> Add TextWatcher in Textfield

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
- components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTexfieldAttrsParser.kt
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
- Se da la opción que el counter sea visible o no.
- Se da la opción de cambiar sólo el suffix sin necesidad de pasarle el listener.
> Add showCounter and setTextAction

- .gitignore
- components/build.gradle
- components/src/main/res/badge/layout/andes_layout_badge_pill.xml
- components/src/main/res/layout/andes_layout_card.xml
- components/src/main/res/progress/values/dimens_progress.xml
- components/src/main/res/textfield/layout/andes_layout_checkbox.xml
- components/src/main/res/textfield/layout/andes_layout_textarea.xml
- components/src/main/res/textfield/layout/andes_layout_textfield.xml
- components/src/main/res/textfield/values/dimens_textfield.xml
- components/src/main/res/thumbnail/layout/andes_layout_thumbnail.xml
- config/android/android-lint-components.xml
- demoapp/build.gradle
- demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/PageIndicator.java
- gradle.properties
Changed many Android Lint linters from warning to error:
- ContentDescription
- PxUsage
- SpUsage
- LabelFor
- UselessParent
Upgraded dexCountGradlePlugin to latest stable release v1.0.3.
Upgraded staticCodeAnalysis to latest stable release v3.2.0 which replace Findbugs with Spotbus.
Also I removed unused properties from `gradle.properties`
PR will continue in another one by fixing & upgrading Detekt.
> Many linters improvements to improve the developer experience

- config/android/android-lint-components.xml
Simply change severity from warning to error to add another check for the Android Lint
> Fix IconDuplicates severity for Android Lint [Trivial]

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/thumbnail/AndesThumbnail.kt
- demoapp/src/main/res/layout/andesui_demoapp_main.xml
Issue -> https://github.com/mercadolibre/fury_andesui-android/issues/150
There is a problem to keep the aspect ratio on a Thumbnail drawable. The current fix uses the internal ImageView drawable content, and when its size change, the drawable content keeps the corresponding aspect ratio. 
Thumbnail
> Fix thumbnail image aspect ratio

- CHANGELOG.md
- demoapp/src/main/AndroidManifest.xml
- demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/MainApplication.kt
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
- gradle.properties
Added auto enabling of Show Taps on API 22 and below.
It writes the System Permissions and enables a Developer Option. 
Because it's highly useful when we record a GIF showing a new feature.
Demo App
> Enable "Show Taps" for API 22 and below

- CHANGELOG.md
- demoapp/build.gradle
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
- dependencies.gradle
We want to detect memory leak in an early stage.
Added leak canary to debug builds only.
It can be disabled from the LeakCanary icon launcher => About section if necessary.
None
> Add Leak Canary v2.5 to debug builds

- components/src/main/java/com/mercadolibre/android/andesui/checkbox/AndesCheckbox.kt
- components/src/main/res/textfield/layout/andes_layout_checkbox.xml
AndesCheckbox needs to be clickable the entire component and not only Checkbox View. This wrong behavior was observed by the UX Team, the entire row should change the state of the checkbox. 
Set the entire AndesCheckbox component as clickable.
The UX team behind Andes keeps all the Andes Components inside the Frontify site. Each component has its own section. Let us know the section of the component you want to …
> Fix/ set checkbox component clickable

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
- components/src/test/java/com/mercadolibre/android/andesui/textfield/AndesTextfieldTest.kt
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
- gradle.properties
Se agrega FocusChangedListener al EditText de AndesTextField
AndesTextField …
> Added focus listener to EditText inside of AndesTextField

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/tag/choice/AndesTagChoiceStateInterface.kt
Mediante este  PR se pretende cambiar a pedido de UX, el color default que se implemente en los componentes de Left Content para TagChoice a #CC000000
The UX team behind Andes keeps all the Andes Components …
> AndesTag Left content default color change

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/textfield/content/AndesTextfieldContentInterface.kt
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
- gradle.properties
Fix the size of the right and left componente of text
TextField
> Fix the size of the right and left componente of text

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/card/AndesCard.kt
- components/src/test/java/com/mercadolibre/android/andesui/card/AndesCardTest.kt
- gradle.properties
Fix aplicado al cambio del siguiente PR: [PR del cambio original](https://github.com/mercadolibre/fury_andesui-android/pull/206)
RFC: [documento RFC](https://docs.google.com/document/d/1Nc22biT3CclP_hmpG1JC3uUc_58NZx612BdlYsCq2xE/edit#heading=h.ixm8d2k39d9a)
Se corrige el seteo de la property **bodyPadding** cuando este tiene la property **padding** seteada directamente del XML en **NONE**
¿Qué sucedía? Al …
> fix bodypadding

- CHANGELOG.md
- components/src/main/java/com/mercadolibre/android/andesui/button/AndesButton.kt
- components/src/main/java/com/mercadolibre/android/andesui/button/factory/AndesButtonAttrsParser.kt
- components/src/main/java/com/mercadolibre/android/andesui/button/factory/AndesButtonConfigurationFactory.kt
- components/src/main/java/com/mercadolibre/android/andesui/button/factory/AndesButtonMargin.kt
- components/src/main/java/com/mercadolibre/android/andesui/button/size/AndesButtonSizeInterface.kt
- components/src/test/java/com/mercadolibre/android/andesui/button/AndesButtonSizeTest.kt
- components/src/test/java/com/mercadolibre/android/andesui/button/AndesButtonTest.kt
- demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ButtonShowcaseActivity.kt
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
- demoapp/src/main/res/values/strings.xml
- gradle.properties
This new feature allows the user to set a Drawable programmatically.
AndesButton
> AndesButton with drawable support

- CHANGELOG.md
- coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/CoachmarkScrollessView.kt
- coachmark/src/main/res/layout/andes_walkthrough_scrolless_container.xml
- coachmark/src/main/res/layout/andes_walkthrough_scrolless_message.xml
- demoapp/src/main/res/raw/andesui_demoapp_changelog.md
Se realizaron modificaciones basicas para permitir la navegacion. 
- Se hace foco en el coachmark
- Se marcan las flechas como no importantes para talkback.
- Se agrega etiqueta al boton que permite cerrar el coahmark.
Whether you are an Android or iOS developer and if you're still …
> accessibility scrolless coachmark
